### ISSUE TITLE
Move source code from docs folder

### ISSUE THREAD

**Issue by vladislav-kir** [SSWConsulting/SSW.Dory#83]
Cc: @adamcogan, @Jord-Gui, @ricksu978 

As per the conversation with @adamcogan, he suggested moving out the source code from "docs" folder, into a new "content" folder.

**Comment by Jord-Gui** [comment]
FYI forgot to mention yesterday that the reason it was initially put into docs was because when it was deployed using GitHub Pages, the [official documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) mentioned deploying from a 'docs' folder. That carried over when migrating to NextJS + Azure

<img width="766" alt="image" src="https://github.com/SSWConsulting/SSW.Dory/assets/41951199/10ba06a0-c56b-41bb-b757-9ebbdd39779f">\
**Figure: GitHub Pages documentation on configuring a publishing source mentioning a 'docs' folder**

**Comment by Jord-Gui** [comment]
✅ Done - source code for website is now in 'content' folder

![Image](https://github.com/SSWConsulting/SSW.Dory/assets/41951199/3c54d836-b72a-496a-bac6-ea8a492d633c)
